(function(c){c.sub||(jQuery.sub=function(){function c(f,e){return new c.fn.init(f,e)}jQuery.extend(!0,c,this);c.superclass=this;c.fn=c.prototype=this();c.fn.constructor=c;c.sub=this.sub;c.fn.init=function(f,e){e&&e instanceof jQuery&&!(e instanceof c)&&(e=c(e));return jQuery.fn.init.call(this,f,e,h)};c.fn.init.prototype=c.fn;var h=c(document);return c});var h=c.sub();"find has not filter is closest index add addBack".split(" ").forEach(function(d){var k=h.fn[d];h.fn[d]=function(){for(var f=[],e,d=
0;d<arguments.length;d++){var g=arguments[d];if(g&&(g.nodeType||g instanceof jQuery)){var r=c(g);e=e||this.root();if(e.is(r)||e.find(r).length){f.push(g);continue}g=[];for(d=0;d<r.length;d++)var l=c(r[d]).capturePath(e.data("branch")),g=g.concat(e.yieldPath(l).get());g=c(g)}f.push(g)}f=k.apply(this,f);return f instanceof jQuery?h(f.get()):f}});c.fn.root=function(){var d=this.map(function(){for(var d=c(this),f;d.length;)f=d,d=d.parent();return f.get(0)}).get();return c(c.unique(d))};c.fn.branch=function(c,
k){return h(this.clone(void 0===c?!1:c,void 0===k?!1:k).data("branch",this).get())}})(jQuery);
(function(c){c.fn.path=function(h){var d=[],k=!!h;h=c(h||window.document);this.each(function(){for(var f=[],e=c(this),m=e.parent();m.length&&!e.is(h);m=m.parent()){var g=e.get(0).tagName.toLowerCase();f.push(g+":eq("+m.children(g).index(e)+")");e=m}(!k||m.length||e.is(h))&&d.push(f.reverse().join(" > "))});return d.join(", ")};c.fn.capturePath=function(h){var d=this,k=this.get(0)instanceof Text,f;if(k){var d=this.parent(),e=d.contents();for(f=0;f<e.length&&e[f]!==this[0];f++);}var m=d.path(h),g=d.is(h);
return function(d){d||(d=this instanceof jQuery||this.nodeType?this:document);var e=c(d).find(m);g&&(e=c(d));return k?c(e.contents()[f]):e}};c.fn.yieldPath=function(c){return"function"===typeof c?c(this):this.find(c)}})(jQuery);
(function(c){var h=function(a,b){var c={};a.forEach(function(a){(a=b(a))&&(c[a[0]]=a[1])});return c},d=h("childList attributes characterData subtree attributeOldValue characterDataOldValue attributeFilter".split(" "),function(a){return[a.toLowerCase(),a]}),k=h(Object.keys(d),function(a){if("attributefilter"!==a)return[d[a],!0]}),f=h(["added","removed"],function(a){return[a.toLowerCase(),a]}),e=c([]),m=function(a){if("object"===typeof a)return a;a=a.split(/\s+/);var b={};a.forEach(function(a){a=a.toLowerCase();
if(!d[a]&&!f[a])throw Error("Unknown option "+a);b[d[a]||f[a]]=!0});return b},g=function(a){return"["+Object.keys(a).sort().reduce(function(b,c){var d=a[c]&&"object"===typeof a[c]?g(a[c]):a[c];return b+"["+JSON.stringify(c)+":"+d+"]"},"")+"]"},r=window.MutationObserver||window.WebKitMutationObserver,l=function(a,b,p,d){this._originalOptions=c.extend({},b);b=c.extend({},b);this.attributeFilter=b.attributeFilter;delete b.attributeFilter;p&&(b.subtree=!0);b.childList&&(b.added=!0,b.removed=!0);if(b.added||
b.removed)b.childList=!0;this.target=c(a);this.options=b;this.selector=p;this.handler=d};l.prototype.is=function(a,b,c){return g(this._originalOptions)===g(a)&&this.selector===b&&this.handler===c};l.prototype.match=function(a){var b=this.options,p=a.type;if(!this.options[p])return e;if(this.selector)switch(p){case "attributes":if(!this._matchAttributeFilter(a))break;case "characterData":return this._matchAttributesAndCharacterData(a);case "childList":if(a.addedNodes&&a.addedNodes.length&&b.added&&
(p=this._matchAddedNodes(a),p.length))return p;if(a.removedNodes&&a.removedNodes.length&&b.removed)return this._matchRemovedNodes(a)}else{var d=a.target instanceof Text?c(a.target).parent():c(a.target);if(!b.subtree&&d.get(0)!==this.target.get(0))return e;switch(p){case "attributes":if(!this._matchAttributeFilter(a))break;case "characterData":return this.target;case "childList":if(a.addedNodes&&a.addedNodes.length&&b.added||a.removedNodes&&a.removedNodes.length&&b.removed)return this.target}}return e};
l.prototype._matchAttributesAndCharacterData=function(a){return this._matchSelector(this.target,[a.target])};l.prototype._matchAddedNodes=function(a){return this._matchSelector(this.target,a.addedNodes)};l.prototype._matchRemovedNodes=function(a){var b=this.target.branch(),d=Array.prototype.slice.call(a.removedNodes).map(function(a){return c(a).clone(!1,!1).get(0)});a.previousSibling?b.find(a.previousSibling).after(d):a.nextSibling?b.find(a.nextSibling).before(d):(b.is(a.target)?b:b.find(a.target)).empty().append(d);
return this._matchSelector(b,d).length?c(a.target):e};l.prototype._matchSelector=function(a,b){var d=a.find(this.selector);b=Array.prototype.slice.call(b);return d=d.filter(function(){var a=this;return b.some(function(b){return b instanceof Text?b.parentNode===a:b===a||c(b).has(a).length})})};l.prototype._matchAttributeFilter=function(a){return this.attributeFilter&&this.attributeFilter.length?0<=this.attributeFilter.indexOf(a.attributeName):!0};var q=function(a){this.patterns=[];this._target=a;this._observer=
null};q.prototype.observe=function(a,b,c){var d=this;this._observer?this._observer.disconnect():this._observer=new r(function(a){a.forEach(function(a){d.patterns.forEach(function(b){var c=b.match(a);c.length&&c.each(function(){b.handler.call(this,a)})})})});this.patterns.push(new l(this._target,a,b,c));this._observer.observe(this._target,this._collapseOptions())};q.prototype.disconnect=function(a,b,c){var d=this;this._observer&&(this.patterns.filter(function(d){return d.is(a,b,c)}).forEach(function(a){a=
d.patterns.indexOf(a);d.patterns.splice(a,1)}),this.patterns.length||this._observer.disconnect())};q.prototype.disconnectAll=function(){this._observer&&(this.patterns=[],this._observer.disconnect())};q.prototype.pause=function(){this._observer&&this._observer.disconnect()};q.prototype.resume=function(){this._observer&&this._observer.observe(this._target,this._collapseOptions())};q.prototype._collapseOptions=function(){var a={};this.patterns.forEach(function(b){var d=a.attributes&&a.attributeFilter;
if(!d&&a.attributes||!b.attributeFilter)d&&b.options.attributes&&!b.attributeFilter&&delete a.attributeFilter;else{var e={},f=[];(a.attributeFilter||[]).concat(b.attributeFilter).forEach(function(a){e[a]||(f.push(a),e[a]=1)});a.attributeFilter=f}c.extend(a,b.options)});Object.keys(f).forEach(function(b){delete a[f[b]]});return a};var n=function(a){this.patterns=[];this._paused=!1;this._target=a;this._events={};this._handler=this._handler.bind(this)};n.prototype.NS=".jQueryObserve";n.prototype.observe=
function(a,b,d){a=new l(this._target,a,b,d);c(this._target);a.options.childList&&(this._addEvent("DOMNodeInserted"),this._addEvent("DOMNodeRemoved"));a.options.attributes&&this._addEvent("DOMAttrModified");a.options.characterData&&this._addEvent("DOMCharacerDataModified");this.patterns.push(a)};n.prototype.disconnect=function(a,b,d){var e=c(this._target),f=this;this.patterns.filter(function(c){return c.is(a,b,d)}).forEach(function(a){a=f.patterns.indexOf(a);f.patterns.splice(a,1)});var g=this.patterns.reduce(function(a,
b){b.options.childList&&(a.DOMNodeInserted=!0,a.DOMNodeRemoved=!0);b.options.attributes&&(a.DOMAttrModified=!0);b.options.characterData&&(a.DOMCharacerDataModified=!0);return a},{});Object.keys(this._events).forEach(function(a){g[a]||(delete f._events[a],e.off(a+f.NS,f._handler))})};n.prototype.disconnectAll=function(){var a=c(this._target),b;for(b in this._events)a.off(b+this.NS,this._handler);this._events={};this.patterns=[]};n.prototype.pause=function(){this._paused=!0};n.prototype.resume=function(){this._paused=
!1};n.prototype._handler=function(a){if(!this._paused){var b={type:null,target:null,addedNodes:null,removedNodes:null,previousSibling:null,nextSibling:null,attributeName:null,attributeNamespace:null,oldValue:null};switch(a.type){case "DOMAttrModified":b.type="attributes";b.target=a.target;b.attributeName=a.attrName;b.oldValue=a.prevValue;break;case "DOMCharacerDataModified":b.type="characterData";b.target=c(a.target).parent().get(0);b.attributeName=a.attrName;b.oldValue=a.prevValue;break;case "DOMNodeInserted":b.type=
"childList";b.target=a.relatedNode;b.addedNodes=[a.target];b.removedNodes=[];break;case "DOMNodeRemoved":b.type="childList",b.target=a.relatedNode,b.addedNodes=[],b.removedNodes=[a.target]}for(a=0;a<this.patterns.length;a++){var d=this.patterns[a],e=d.match(b);e.length&&e.each(function(){d.handler.call(this,b)})}}};n.prototype._addEvent=function(a){this._events[a]||(c(this._target).on(a+this.NS,this._handler),this._events[a]=!0)};c.Observe={Pattern:l,MutationObserver:q,DOMEventObserver:n};c.fn.observe=
function(a,b,d){b?d||(d=b,b=null):(d=a,a=k);return this.each(function(){var e=c(this),f=e.data("observer");f||(f=r?new q(this):new n(this),e.data("observer",f));a=m(a);f.observe(a,b,d)})};c.fn.disconnect=function(a,b,d){a&&(b?d||(d=b,b=null):(d=a,a=k));return this.each(function(){var e=c(this),f=e.data("observer");f&&(a?(a=m(a),f.disconnect(a,b,d)):(f.disconnectAll(),e.removeData("observer")))})}})(jQuery);
