(function(c){c.fn.path=function(j){var b=[],l=!!j,j=c(j||window.document);this.each(function(){for(var e=[],d=c(this),h=d.parent();h.length&&!d.is(j);h=h.parent()){var f=d.get(0).tagName.toLowerCase();e.push(f+":eq("+h.children(f).index(d)+")");d=h}(!l||h.length||d.is(j))&&b.push(e.reverse().join(" > "))});return b.join(", ")};c.fn.capturePath=function(j){var b=this,l=this.get(0)instanceof Text,e;if(l){var b=this.parent(),d=b.contents();for(e=0;e<d.length&&d[e]!==this[0];e++);}var h=b.path(j);return function(b){b||
(b=this instanceof jQuery||this.nodeType?this:document);b=c(b).find(h);return!l?b:c(b.contents()[e])}};c.fn.yieldPath=function(c){return"function"===typeof c?c(this):this.find(c)}})(jQuery);
(function(c){c.sub||(jQuery.sub=function(){function b(c,d){return new b.fn.init(c,d)}jQuery.extend(!0,b,this);b.superclass=this;b.fn=b.prototype=this();b.fn.constructor=b;b.sub=this.sub;b.fn.init=function(e,d){d&&(d instanceof jQuery&&!(d instanceof b))&&(d=b(d));return jQuery.fn.init.call(this,e,d,c)};b.fn.init.prototype=b.fn;var c=b(document);return b});var j=c.sub();"find has not filter is closest index add addBack".split(" ").forEach(function(b){var l=j.fn[b];j.fn[b]=function(){for(var b=[],d,
h=0;h<arguments.length;h++){var f=arguments[h];if(f&&(f.nodeType||f instanceof jQuery)){var n=c(f);d=d||this.root();if(d.find(n).length){b.push(f);continue}f=[];for(h=0;h<n.length;h++)var k=c(n[h]).capturePath(d.data("branch")),f=f.concat(d.yieldPath(k).get());f=c(f)}b.push(f)}return j(l.apply(this,b).get())}});c.fn.root=function(){var b=this.map(function(){for(var b=c(this),e;b.length;)e=b,b=b.parent();return e.get(0)}).get();return c(c.unique(b))};c.fn.branch=function(b,c){return j(this.clone(void 0===
b?!1:b,void 0===c?!1:c).data("branch",this).get())}})(jQuery);
(function(c){var j=function(a,g){var i={};a.forEach(function(a){(a=g(a))&&(i[a[0]]=a[1])});return i},b=j("childList attributes characterData subtree attributeOldValue characterDataOldValue attributeFilter".split(" "),function(a){return[a.toLowerCase(),a]}),l=j(Object.keys(b),function(a){if("attributefilter"!==a)return[b[a],!0]}),e=j(["added","removed"],function(a){return[a.toLowerCase(),a]}),d=c([]),h=function(a){if("object"===typeof a)return a;var a=a.split(/\s+/),g={};a.forEach(function(a){a=a.toLowerCase();
if(!b[a]&&!e[a])throw Error("Unknown option "+a);g[b[a]||e[a]]=!0});return g},f=function(a){return"["+Object.keys(a).sort().reduce(function(g,b){var c=a[b]&&"object"===typeof a[b]?f(a[b]):a[b];return g+"["+JSON.stringify(b)+":"+c+"]"},"")+"]"},n=window.MutationObserver||window.WebKitMutationObserver,k=function(a,g,b,d){this._originalOptions=c.extend({},g);g=c.extend({},g);this.attributeFilter=g.attributeFilter;delete g.attributeFilter;b&&(g.subtree=!0);g.childList&&(g.added=!0,g.removed=!0);if(g.added||
g.removed)g.childList=!0;this.target=c(a);this.options=g;this.selector=b;this.handler=d};k.prototype.is=function(a,g,b){return f(this._originalOptions)===f(a)&&this.selector===g&&this.handler===b};k.prototype.match=function(a){var b=this.options,i=a.type;if(!this.options[i])return d;if(this.selector)switch(i){case "attributes":if(!this._matchAttributeFilter(a))break;case "characterData":return this._matchAttributesAndCharacterData(a);case "childList":if(a.addedNodes&&(a.addedNodes.length&&b.added)&&
(i=this._matchAddedNodes(a),i.length))return i;if(a.removedNodes&&a.removedNodes.length&&b.removed)return this._matchRemovedNodes(a)}else switch(i){case "attributes":if(!this._matchAttributeFilter(a))break;case "characterData":if(!b.subtree&&a.target!==this.target.get(0))break;return c(a.target);case "childList":if(!b.subtree&&a.target!==this.target.get(0))break;if(a.addedNodes&&a.addedNodes.length&&b.added||a.removedNodes&&a.removedNodes.length&&b.removed)return c(a.target)}return d};k.prototype._matchAttributesAndCharacterData=
function(a){return this._matchSelector(this.target,[a.target])};k.prototype._matchAddedNodes=function(a){return this._matchSelector(this.target,a.addedNodes)};k.prototype._matchRemovedNodes=function(a){var b=this.target.branch(),i=Array.prototype.slice.call(a.removedNodes);a.previousSibling?b.find(a.previousSibling).after(i):a.nextSibling?b.find(a.nextSibling).before(i):b.find(a.target).empty().append(i);return this._matchSelector(b,i).length?c(a.target):d};k.prototype._matchSelector=function(a,b){var i=
a.find(this.selector),b=c(Array.prototype.slice.call(b).map(function(a){return a instanceof Text?c(a).parent().get(0):a})),i=i.filter(function(){return b.is(this)||b.has(this).length});return i.length?i:d};k.prototype._matchAttributeFilter=function(a){return this.attributeFilter&&this.attributeFilter.length?0<=this.attributeFilter.indexOf(a.attributeName):!0};var m=function(a){this.patterns=[];this._target=a;this._observer=null};m.prototype.observe=function(a,b,c){var d=this;this._observer?this._observer.disconnect():
this._observer=new n(function(a){a.forEach(function(a){for(var b=0;b<d.patterns.length;b++){var c=d.patterns[b],g=c.match(a);g.length&&g.each(function(){c.handler.call(this,a)})}})});this.patterns.push(new k(this._target,a,b,c));this._observer.observe(this._target,this._collapseOptions())};m.prototype.disconnect=function(a,b,c){var d=this;this._observer&&(this.patterns.filter(function(d){return d.is(a,b,c)}).forEach(function(a){a=d.patterns.indexOf(a);d.patterns.splice(a,1)}),this.patterns.length||
this._observer.disconnect())};m.prototype.disconnectAll=function(){this._observer&&(this.patterns=[],this._observer.disconnect())};m.prototype.pause=function(){this._observer&&this._observer.disconnect()};m.prototype.resume=function(){this._observer&&this._observer.observe(this._target,this._collapseOptions())};m.prototype._collapseOptions=function(){var a={};this.patterns.forEach(function(b){var d=a.attributes&&a.attributeFilter;if((d||!a.attributes)&&b.attributeFilter){var h={},e=[];(a.attributeFilter||
[]).concat(b.attributeFilter).forEach(function(a){h[a]||(e.push(a),h[a]=1)});a.attributeFilter=e}else d&&(b.options.attributes&&!b.attributeFilter)&&delete a.attributeFilter;c.extend(a,b.options)});Object.keys(e).forEach(function(b){delete a[e[b]]});return a};c.fn.observe=function(a,b,d){b?d||(d=b,b=null):(d=a,a=l);return this.each(function(){var e=c(this),f=e.data("observer");f||(f=new m(this),e.data("observer",f));a=h(a);f.observe(a,b,d)})};c.fn.disconnect=function(a,b,d){a&&(b?d||(d=b,b=null):
(d=a,a=l));return this.each(function(){var e=c(this),f=e.data("observer");f&&(a?(a=h(a),f.disconnect(a,b,d)):(f.disconnectAll(),e.removeData("observer")))})}})(jQuery);
